---
monitoring_prometheus_version: "2.53.2"
monitoring_prometheus_port: "9090"
monitoring_grafana_port: "3000"
monitoring_prometheus_scrape_targets:
  - job_name: "web_node"
    target: "web_node:9100"
  - job_name: "app_node"
    target: "app_node:9100"
  - job_name: "db_node"
    target: "db_node:9100"
